/*
NVIDIA Bare Metal Manager REST API

NVIDIA Bare Metal Manager REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Bare Metal Manager datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the SiteMachineStatsByStatusAndHealth type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteMachineStatsByStatusAndHealth{}

// SiteMachineStatsByStatusAndHealth Machine stats for a Site by status and health
type SiteMachineStatsByStatusAndHealth struct {
	Decommissioned *SiteMachineStatsByHealth `json:"Decommissioned,omitempty"`
	Error *SiteMachineStatsByHealth `json:"Error,omitempty"`
	Initializing *SiteMachineStatsByHealth `json:"Initializing,omitempty"`
	InUse *SiteMachineStatsByHealth `json:"InUse,omitempty"`
	Maintenance *SiteMachineStatsByHealth `json:"Maintenance,omitempty"`
	Ready *SiteMachineStatsByHealth `json:"Ready,omitempty"`
	Reset *SiteMachineStatsByHealth `json:"Reset,omitempty"`
	Unknown *SiteMachineStatsByHealth `json:"Unknown,omitempty"`
}

// NewSiteMachineStatsByStatusAndHealth instantiates a new SiteMachineStatsByStatusAndHealth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteMachineStatsByStatusAndHealth() *SiteMachineStatsByStatusAndHealth {
	this := SiteMachineStatsByStatusAndHealth{}
	return &this
}

// NewSiteMachineStatsByStatusAndHealthWithDefaults instantiates a new SiteMachineStatsByStatusAndHealth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteMachineStatsByStatusAndHealthWithDefaults() *SiteMachineStatsByStatusAndHealth {
	this := SiteMachineStatsByStatusAndHealth{}
	return &this
}

// GetDecommissioned returns the Decommissioned field value if set, zero value otherwise.
func (o *SiteMachineStatsByStatusAndHealth) GetDecommissioned() SiteMachineStatsByHealth {
	if o == nil || IsNil(o.Decommissioned) {
		var ret SiteMachineStatsByHealth
		return ret
	}
	return *o.Decommissioned
}

// GetDecommissionedOk returns a tuple with the Decommissioned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStatsByStatusAndHealth) GetDecommissionedOk() (*SiteMachineStatsByHealth, bool) {
	if o == nil || IsNil(o.Decommissioned) {
		return nil, false
	}
	return o.Decommissioned, true
}

// HasDecommissioned returns a boolean if a field has been set.
func (o *SiteMachineStatsByStatusAndHealth) HasDecommissioned() bool {
	if o != nil && !IsNil(o.Decommissioned) {
		return true
	}

	return false
}

// SetDecommissioned gets a reference to the given SiteMachineStatsByHealth and assigns it to the Decommissioned field.
func (o *SiteMachineStatsByStatusAndHealth) SetDecommissioned(v SiteMachineStatsByHealth) {
	o.Decommissioned = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *SiteMachineStatsByStatusAndHealth) GetError() SiteMachineStatsByHealth {
	if o == nil || IsNil(o.Error) {
		var ret SiteMachineStatsByHealth
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStatsByStatusAndHealth) GetErrorOk() (*SiteMachineStatsByHealth, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *SiteMachineStatsByStatusAndHealth) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given SiteMachineStatsByHealth and assigns it to the Error field.
func (o *SiteMachineStatsByStatusAndHealth) SetError(v SiteMachineStatsByHealth) {
	o.Error = &v
}

// GetInitializing returns the Initializing field value if set, zero value otherwise.
func (o *SiteMachineStatsByStatusAndHealth) GetInitializing() SiteMachineStatsByHealth {
	if o == nil || IsNil(o.Initializing) {
		var ret SiteMachineStatsByHealth
		return ret
	}
	return *o.Initializing
}

// GetInitializingOk returns a tuple with the Initializing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStatsByStatusAndHealth) GetInitializingOk() (*SiteMachineStatsByHealth, bool) {
	if o == nil || IsNil(o.Initializing) {
		return nil, false
	}
	return o.Initializing, true
}

// HasInitializing returns a boolean if a field has been set.
func (o *SiteMachineStatsByStatusAndHealth) HasInitializing() bool {
	if o != nil && !IsNil(o.Initializing) {
		return true
	}

	return false
}

// SetInitializing gets a reference to the given SiteMachineStatsByHealth and assigns it to the Initializing field.
func (o *SiteMachineStatsByStatusAndHealth) SetInitializing(v SiteMachineStatsByHealth) {
	o.Initializing = &v
}

// GetInUse returns the InUse field value if set, zero value otherwise.
func (o *SiteMachineStatsByStatusAndHealth) GetInUse() SiteMachineStatsByHealth {
	if o == nil || IsNil(o.InUse) {
		var ret SiteMachineStatsByHealth
		return ret
	}
	return *o.InUse
}

// GetInUseOk returns a tuple with the InUse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStatsByStatusAndHealth) GetInUseOk() (*SiteMachineStatsByHealth, bool) {
	if o == nil || IsNil(o.InUse) {
		return nil, false
	}
	return o.InUse, true
}

// HasInUse returns a boolean if a field has been set.
func (o *SiteMachineStatsByStatusAndHealth) HasInUse() bool {
	if o != nil && !IsNil(o.InUse) {
		return true
	}

	return false
}

// SetInUse gets a reference to the given SiteMachineStatsByHealth and assigns it to the InUse field.
func (o *SiteMachineStatsByStatusAndHealth) SetInUse(v SiteMachineStatsByHealth) {
	o.InUse = &v
}

// GetMaintenance returns the Maintenance field value if set, zero value otherwise.
func (o *SiteMachineStatsByStatusAndHealth) GetMaintenance() SiteMachineStatsByHealth {
	if o == nil || IsNil(o.Maintenance) {
		var ret SiteMachineStatsByHealth
		return ret
	}
	return *o.Maintenance
}

// GetMaintenanceOk returns a tuple with the Maintenance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStatsByStatusAndHealth) GetMaintenanceOk() (*SiteMachineStatsByHealth, bool) {
	if o == nil || IsNil(o.Maintenance) {
		return nil, false
	}
	return o.Maintenance, true
}

// HasMaintenance returns a boolean if a field has been set.
func (o *SiteMachineStatsByStatusAndHealth) HasMaintenance() bool {
	if o != nil && !IsNil(o.Maintenance) {
		return true
	}

	return false
}

// SetMaintenance gets a reference to the given SiteMachineStatsByHealth and assigns it to the Maintenance field.
func (o *SiteMachineStatsByStatusAndHealth) SetMaintenance(v SiteMachineStatsByHealth) {
	o.Maintenance = &v
}

// GetReady returns the Ready field value if set, zero value otherwise.
func (o *SiteMachineStatsByStatusAndHealth) GetReady() SiteMachineStatsByHealth {
	if o == nil || IsNil(o.Ready) {
		var ret SiteMachineStatsByHealth
		return ret
	}
	return *o.Ready
}

// GetReadyOk returns a tuple with the Ready field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStatsByStatusAndHealth) GetReadyOk() (*SiteMachineStatsByHealth, bool) {
	if o == nil || IsNil(o.Ready) {
		return nil, false
	}
	return o.Ready, true
}

// HasReady returns a boolean if a field has been set.
func (o *SiteMachineStatsByStatusAndHealth) HasReady() bool {
	if o != nil && !IsNil(o.Ready) {
		return true
	}

	return false
}

// SetReady gets a reference to the given SiteMachineStatsByHealth and assigns it to the Ready field.
func (o *SiteMachineStatsByStatusAndHealth) SetReady(v SiteMachineStatsByHealth) {
	o.Ready = &v
}

// GetReset returns the Reset field value if set, zero value otherwise.
func (o *SiteMachineStatsByStatusAndHealth) GetReset() SiteMachineStatsByHealth {
	if o == nil || IsNil(o.Reset) {
		var ret SiteMachineStatsByHealth
		return ret
	}
	return *o.Reset
}

// GetResetOk returns a tuple with the Reset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStatsByStatusAndHealth) GetResetOk() (*SiteMachineStatsByHealth, bool) {
	if o == nil || IsNil(o.Reset) {
		return nil, false
	}
	return o.Reset, true
}

// HasReset returns a boolean if a field has been set.
func (o *SiteMachineStatsByStatusAndHealth) HasReset() bool {
	if o != nil && !IsNil(o.Reset) {
		return true
	}

	return false
}

// SetReset gets a reference to the given SiteMachineStatsByHealth and assigns it to the Reset field.
func (o *SiteMachineStatsByStatusAndHealth) SetReset(v SiteMachineStatsByHealth) {
	o.Reset = &v
}

// GetUnknown returns the Unknown field value if set, zero value otherwise.
func (o *SiteMachineStatsByStatusAndHealth) GetUnknown() SiteMachineStatsByHealth {
	if o == nil || IsNil(o.Unknown) {
		var ret SiteMachineStatsByHealth
		return ret
	}
	return *o.Unknown
}

// GetUnknownOk returns a tuple with the Unknown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStatsByStatusAndHealth) GetUnknownOk() (*SiteMachineStatsByHealth, bool) {
	if o == nil || IsNil(o.Unknown) {
		return nil, false
	}
	return o.Unknown, true
}

// HasUnknown returns a boolean if a field has been set.
func (o *SiteMachineStatsByStatusAndHealth) HasUnknown() bool {
	if o != nil && !IsNil(o.Unknown) {
		return true
	}

	return false
}

// SetUnknown gets a reference to the given SiteMachineStatsByHealth and assigns it to the Unknown field.
func (o *SiteMachineStatsByStatusAndHealth) SetUnknown(v SiteMachineStatsByHealth) {
	o.Unknown = &v
}

func (o SiteMachineStatsByStatusAndHealth) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteMachineStatsByStatusAndHealth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Decommissioned) {
		toSerialize["Decommissioned"] = o.Decommissioned
	}
	if !IsNil(o.Error) {
		toSerialize["Error"] = o.Error
	}
	if !IsNil(o.Initializing) {
		toSerialize["Initializing"] = o.Initializing
	}
	if !IsNil(o.InUse) {
		toSerialize["InUse"] = o.InUse
	}
	if !IsNil(o.Maintenance) {
		toSerialize["Maintenance"] = o.Maintenance
	}
	if !IsNil(o.Ready) {
		toSerialize["Ready"] = o.Ready
	}
	if !IsNil(o.Reset) {
		toSerialize["Reset"] = o.Reset
	}
	if !IsNil(o.Unknown) {
		toSerialize["Unknown"] = o.Unknown
	}
	return toSerialize, nil
}

type NullableSiteMachineStatsByStatusAndHealth struct {
	value *SiteMachineStatsByStatusAndHealth
	isSet bool
}

func (v NullableSiteMachineStatsByStatusAndHealth) Get() *SiteMachineStatsByStatusAndHealth {
	return v.value
}

func (v *NullableSiteMachineStatsByStatusAndHealth) Set(val *SiteMachineStatsByStatusAndHealth) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteMachineStatsByStatusAndHealth) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteMachineStatsByStatusAndHealth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteMachineStatsByStatusAndHealth(val *SiteMachineStatsByStatusAndHealth) *NullableSiteMachineStatsByStatusAndHealth {
	return &NullableSiteMachineStatsByStatusAndHealth{value: val, isSet: true}
}

func (v NullableSiteMachineStatsByStatusAndHealth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteMachineStatsByStatusAndHealth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


