/*
NVIDIA Bare Metal Manager REST API

NVIDIA Bare Metal Manager REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Bare Metal Manager datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the SiteMachineStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteMachineStats{}

// SiteMachineStats Machine stats for a Site
type SiteMachineStats struct {
	Total *int32 `json:"total,omitempty"`
	TotalByStatus *SiteMachineStatsByStatus `json:"totalByStatus,omitempty"`
	TotalByHealth *SiteMachineStatsByHealth `json:"totalByHealth,omitempty"`
	TotalByStatusAndHealth *SiteMachineStatsByStatusAndHealth `json:"totalByStatusAndHealth,omitempty"`
	TotalByAllocation *SiteMachineStatsByAllocation `json:"totalByAllocation,omitempty"`
}

// NewSiteMachineStats instantiates a new SiteMachineStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteMachineStats() *SiteMachineStats {
	this := SiteMachineStats{}
	return &this
}

// NewSiteMachineStatsWithDefaults instantiates a new SiteMachineStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteMachineStatsWithDefaults() *SiteMachineStats {
	this := SiteMachineStats{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *SiteMachineStats) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStats) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *SiteMachineStats) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *SiteMachineStats) SetTotal(v int32) {
	o.Total = &v
}

// GetTotalByStatus returns the TotalByStatus field value if set, zero value otherwise.
func (o *SiteMachineStats) GetTotalByStatus() SiteMachineStatsByStatus {
	if o == nil || IsNil(o.TotalByStatus) {
		var ret SiteMachineStatsByStatus
		return ret
	}
	return *o.TotalByStatus
}

// GetTotalByStatusOk returns a tuple with the TotalByStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStats) GetTotalByStatusOk() (*SiteMachineStatsByStatus, bool) {
	if o == nil || IsNil(o.TotalByStatus) {
		return nil, false
	}
	return o.TotalByStatus, true
}

// HasTotalByStatus returns a boolean if a field has been set.
func (o *SiteMachineStats) HasTotalByStatus() bool {
	if o != nil && !IsNil(o.TotalByStatus) {
		return true
	}

	return false
}

// SetTotalByStatus gets a reference to the given SiteMachineStatsByStatus and assigns it to the TotalByStatus field.
func (o *SiteMachineStats) SetTotalByStatus(v SiteMachineStatsByStatus) {
	o.TotalByStatus = &v
}

// GetTotalByHealth returns the TotalByHealth field value if set, zero value otherwise.
func (o *SiteMachineStats) GetTotalByHealth() SiteMachineStatsByHealth {
	if o == nil || IsNil(o.TotalByHealth) {
		var ret SiteMachineStatsByHealth
		return ret
	}
	return *o.TotalByHealth
}

// GetTotalByHealthOk returns a tuple with the TotalByHealth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStats) GetTotalByHealthOk() (*SiteMachineStatsByHealth, bool) {
	if o == nil || IsNil(o.TotalByHealth) {
		return nil, false
	}
	return o.TotalByHealth, true
}

// HasTotalByHealth returns a boolean if a field has been set.
func (o *SiteMachineStats) HasTotalByHealth() bool {
	if o != nil && !IsNil(o.TotalByHealth) {
		return true
	}

	return false
}

// SetTotalByHealth gets a reference to the given SiteMachineStatsByHealth and assigns it to the TotalByHealth field.
func (o *SiteMachineStats) SetTotalByHealth(v SiteMachineStatsByHealth) {
	o.TotalByHealth = &v
}

// GetTotalByStatusAndHealth returns the TotalByStatusAndHealth field value if set, zero value otherwise.
func (o *SiteMachineStats) GetTotalByStatusAndHealth() SiteMachineStatsByStatusAndHealth {
	if o == nil || IsNil(o.TotalByStatusAndHealth) {
		var ret SiteMachineStatsByStatusAndHealth
		return ret
	}
	return *o.TotalByStatusAndHealth
}

// GetTotalByStatusAndHealthOk returns a tuple with the TotalByStatusAndHealth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStats) GetTotalByStatusAndHealthOk() (*SiteMachineStatsByStatusAndHealth, bool) {
	if o == nil || IsNil(o.TotalByStatusAndHealth) {
		return nil, false
	}
	return o.TotalByStatusAndHealth, true
}

// HasTotalByStatusAndHealth returns a boolean if a field has been set.
func (o *SiteMachineStats) HasTotalByStatusAndHealth() bool {
	if o != nil && !IsNil(o.TotalByStatusAndHealth) {
		return true
	}

	return false
}

// SetTotalByStatusAndHealth gets a reference to the given SiteMachineStatsByStatusAndHealth and assigns it to the TotalByStatusAndHealth field.
func (o *SiteMachineStats) SetTotalByStatusAndHealth(v SiteMachineStatsByStatusAndHealth) {
	o.TotalByStatusAndHealth = &v
}

// GetTotalByAllocation returns the TotalByAllocation field value if set, zero value otherwise.
func (o *SiteMachineStats) GetTotalByAllocation() SiteMachineStatsByAllocation {
	if o == nil || IsNil(o.TotalByAllocation) {
		var ret SiteMachineStatsByAllocation
		return ret
	}
	return *o.TotalByAllocation
}

// GetTotalByAllocationOk returns a tuple with the TotalByAllocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStats) GetTotalByAllocationOk() (*SiteMachineStatsByAllocation, bool) {
	if o == nil || IsNil(o.TotalByAllocation) {
		return nil, false
	}
	return o.TotalByAllocation, true
}

// HasTotalByAllocation returns a boolean if a field has been set.
func (o *SiteMachineStats) HasTotalByAllocation() bool {
	if o != nil && !IsNil(o.TotalByAllocation) {
		return true
	}

	return false
}

// SetTotalByAllocation gets a reference to the given SiteMachineStatsByAllocation and assigns it to the TotalByAllocation field.
func (o *SiteMachineStats) SetTotalByAllocation(v SiteMachineStatsByAllocation) {
	o.TotalByAllocation = &v
}

func (o SiteMachineStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteMachineStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.TotalByStatus) {
		toSerialize["totalByStatus"] = o.TotalByStatus
	}
	if !IsNil(o.TotalByHealth) {
		toSerialize["totalByHealth"] = o.TotalByHealth
	}
	if !IsNil(o.TotalByStatusAndHealth) {
		toSerialize["totalByStatusAndHealth"] = o.TotalByStatusAndHealth
	}
	if !IsNil(o.TotalByAllocation) {
		toSerialize["totalByAllocation"] = o.TotalByAllocation
	}
	return toSerialize, nil
}

type NullableSiteMachineStats struct {
	value *SiteMachineStats
	isSet bool
}

func (v NullableSiteMachineStats) Get() *SiteMachineStats {
	return v.value
}

func (v *NullableSiteMachineStats) Set(val *SiteMachineStats) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteMachineStats) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteMachineStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteMachineStats(val *SiteMachineStats) *NullableSiteMachineStats {
	return &NullableSiteMachineStats{value: val, isSet: true}
}

func (v NullableSiteMachineStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteMachineStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


