/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the ExpectedMachineUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedMachineUpdateRequest{}

// ExpectedMachineUpdateRequest Request data to update an existing Expected Machine.  Note: BMC credentials (username/password) are only accepted during creation and updates but are not returned in responses.  For single updates (PATCH /expected-machine/{id}), the id field is optional in body and will be ignored if provided (the ID from the URL path is used).  For batch updates (PATCH /expected-machine/batch), the id field is required to identify which Expected Machine to update.
type ExpectedMachineUpdateRequest struct {
	// ID of the Expected Machine to update.  Optional for individual Expected Machine update (ignored if provided, ID from URL path is used).  Required for batch update operations.
	Id NullableString `json:"id,omitempty"`
	// MAC address of the Expected Machine's BMC (Baseboard Management Controller)
	BmcMacAddress NullableString `json:"bmcMacAddress,omitempty" validate:"regexp=^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"`
	// Username for accessing the Expected Machine's BMC
	BmcUsername NullableString `json:"bmcUsername,omitempty"`
	// Password for accessing the Expected Machine's BMC
	BmcPassword NullableString `json:"bmcPassword,omitempty"`
	// Serial number of the Expected Machine's chassis
	ChassisSerialNumber NullableString `json:"chassisSerialNumber,omitempty"`
	// Serial numbers of the Expected Machine's fallback DPUs (Data Processing Units)
	FallbackDPUSerialNumbers []string `json:"fallbackDPUSerialNumbers,omitempty"`
	// Optional ID of the SKU to associate with this Expected Machine
	SkuId NullableString `json:"skuId,omitempty"`
	// Optional rack identifier for this component
	RackId NullableString `json:"rackId,omitempty"`
	// Display name for this component
	Name NullableString `json:"name,omitempty"`
	// Manufacturer of this component
	Manufacturer NullableString `json:"manufacturer,omitempty"`
	// Model of this component
	Model NullableString `json:"model,omitempty"`
	// Description of this component
	Description NullableString `json:"description,omitempty"`
	// Firmware version of this component
	FirmwareVersion NullableString `json:"firmwareVersion,omitempty"`
	// Slot ID within the rack
	SlotId NullableInt32 `json:"slotId,omitempty"`
	// Tray index within the rack
	TrayIdx NullableInt32 `json:"trayIdx,omitempty"`
	// Host ID within the tray
	HostId NullableInt32 `json:"hostId,omitempty"`
	// User-defined key-value pairs for organizing and categorizing Expected Machines
	Labels map[string]string `json:"labels,omitempty"`
}

// NewExpectedMachineUpdateRequest instantiates a new ExpectedMachineUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedMachineUpdateRequest() *ExpectedMachineUpdateRequest {
	this := ExpectedMachineUpdateRequest{}
	return &this
}

// NewExpectedMachineUpdateRequestWithDefaults instantiates a new ExpectedMachineUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedMachineUpdateRequestWithDefaults() *ExpectedMachineUpdateRequest {
	this := ExpectedMachineUpdateRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineUpdateRequest) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineUpdateRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *ExpectedMachineUpdateRequest) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *ExpectedMachineUpdateRequest) SetId(v string) {
	o.Id.Set(&v)
}

// SetIdNil sets the value for Id to be an explicit nil
func (o *ExpectedMachineUpdateRequest) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *ExpectedMachineUpdateRequest) UnsetId() {
	o.Id.Unset()
}

// GetBmcMacAddress returns the BmcMacAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineUpdateRequest) GetBmcMacAddress() string {
	if o == nil || IsNil(o.BmcMacAddress.Get()) {
		var ret string
		return ret
	}
	return *o.BmcMacAddress.Get()
}

// GetBmcMacAddressOk returns a tuple with the BmcMacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineUpdateRequest) GetBmcMacAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BmcMacAddress.Get(), o.BmcMacAddress.IsSet()
}

// HasBmcMacAddress returns a boolean if a field has been set.
func (o *ExpectedMachineUpdateRequest) HasBmcMacAddress() bool {
	if o != nil && o.BmcMacAddress.IsSet() {
		return true
	}

	return false
}

// SetBmcMacAddress gets a reference to the given NullableString and assigns it to the BmcMacAddress field.
func (o *ExpectedMachineUpdateRequest) SetBmcMacAddress(v string) {
	o.BmcMacAddress.Set(&v)
}

// SetBmcMacAddressNil sets the value for BmcMacAddress to be an explicit nil
func (o *ExpectedMachineUpdateRequest) SetBmcMacAddressNil() {
	o.BmcMacAddress.Set(nil)
}

// UnsetBmcMacAddress ensures that no value is present for BmcMacAddress, not even an explicit nil
func (o *ExpectedMachineUpdateRequest) UnsetBmcMacAddress() {
	o.BmcMacAddress.Unset()
}

// GetBmcUsername returns the BmcUsername field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineUpdateRequest) GetBmcUsername() string {
	if o == nil || IsNil(o.BmcUsername.Get()) {
		var ret string
		return ret
	}
	return *o.BmcUsername.Get()
}

// GetBmcUsernameOk returns a tuple with the BmcUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineUpdateRequest) GetBmcUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BmcUsername.Get(), o.BmcUsername.IsSet()
}

// HasBmcUsername returns a boolean if a field has been set.
func (o *ExpectedMachineUpdateRequest) HasBmcUsername() bool {
	if o != nil && o.BmcUsername.IsSet() {
		return true
	}

	return false
}

// SetBmcUsername gets a reference to the given NullableString and assigns it to the BmcUsername field.
func (o *ExpectedMachineUpdateRequest) SetBmcUsername(v string) {
	o.BmcUsername.Set(&v)
}

// SetBmcUsernameNil sets the value for BmcUsername to be an explicit nil
func (o *ExpectedMachineUpdateRequest) SetBmcUsernameNil() {
	o.BmcUsername.Set(nil)
}

// UnsetBmcUsername ensures that no value is present for BmcUsername, not even an explicit nil
func (o *ExpectedMachineUpdateRequest) UnsetBmcUsername() {
	o.BmcUsername.Unset()
}

// GetBmcPassword returns the BmcPassword field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineUpdateRequest) GetBmcPassword() string {
	if o == nil || IsNil(o.BmcPassword.Get()) {
		var ret string
		return ret
	}
	return *o.BmcPassword.Get()
}

// GetBmcPasswordOk returns a tuple with the BmcPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineUpdateRequest) GetBmcPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BmcPassword.Get(), o.BmcPassword.IsSet()
}

// HasBmcPassword returns a boolean if a field has been set.
func (o *ExpectedMachineUpdateRequest) HasBmcPassword() bool {
	if o != nil && o.BmcPassword.IsSet() {
		return true
	}

	return false
}

// SetBmcPassword gets a reference to the given NullableString and assigns it to the BmcPassword field.
func (o *ExpectedMachineUpdateRequest) SetBmcPassword(v string) {
	o.BmcPassword.Set(&v)
}

// SetBmcPasswordNil sets the value for BmcPassword to be an explicit nil
func (o *ExpectedMachineUpdateRequest) SetBmcPasswordNil() {
	o.BmcPassword.Set(nil)
}

// UnsetBmcPassword ensures that no value is present for BmcPassword, not even an explicit nil
func (o *ExpectedMachineUpdateRequest) UnsetBmcPassword() {
	o.BmcPassword.Unset()
}

// GetChassisSerialNumber returns the ChassisSerialNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineUpdateRequest) GetChassisSerialNumber() string {
	if o == nil || IsNil(o.ChassisSerialNumber.Get()) {
		var ret string
		return ret
	}
	return *o.ChassisSerialNumber.Get()
}

// GetChassisSerialNumberOk returns a tuple with the ChassisSerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineUpdateRequest) GetChassisSerialNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ChassisSerialNumber.Get(), o.ChassisSerialNumber.IsSet()
}

// HasChassisSerialNumber returns a boolean if a field has been set.
func (o *ExpectedMachineUpdateRequest) HasChassisSerialNumber() bool {
	if o != nil && o.ChassisSerialNumber.IsSet() {
		return true
	}

	return false
}

// SetChassisSerialNumber gets a reference to the given NullableString and assigns it to the ChassisSerialNumber field.
func (o *ExpectedMachineUpdateRequest) SetChassisSerialNumber(v string) {
	o.ChassisSerialNumber.Set(&v)
}

// SetChassisSerialNumberNil sets the value for ChassisSerialNumber to be an explicit nil
func (o *ExpectedMachineUpdateRequest) SetChassisSerialNumberNil() {
	o.ChassisSerialNumber.Set(nil)
}

// UnsetChassisSerialNumber ensures that no value is present for ChassisSerialNumber, not even an explicit nil
func (o *ExpectedMachineUpdateRequest) UnsetChassisSerialNumber() {
	o.ChassisSerialNumber.Unset()
}

// GetFallbackDPUSerialNumbers returns the FallbackDPUSerialNumbers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineUpdateRequest) GetFallbackDPUSerialNumbers() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.FallbackDPUSerialNumbers
}

// GetFallbackDPUSerialNumbersOk returns a tuple with the FallbackDPUSerialNumbers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineUpdateRequest) GetFallbackDPUSerialNumbersOk() ([]string, bool) {
	if o == nil || IsNil(o.FallbackDPUSerialNumbers) {
		return nil, false
	}
	return o.FallbackDPUSerialNumbers, true
}

// HasFallbackDPUSerialNumbers returns a boolean if a field has been set.
func (o *ExpectedMachineUpdateRequest) HasFallbackDPUSerialNumbers() bool {
	if o != nil && !IsNil(o.FallbackDPUSerialNumbers) {
		return true
	}

	return false
}

// SetFallbackDPUSerialNumbers gets a reference to the given []string and assigns it to the FallbackDPUSerialNumbers field.
func (o *ExpectedMachineUpdateRequest) SetFallbackDPUSerialNumbers(v []string) {
	o.FallbackDPUSerialNumbers = v
}

// GetSkuId returns the SkuId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineUpdateRequest) GetSkuId() string {
	if o == nil || IsNil(o.SkuId.Get()) {
		var ret string
		return ret
	}
	return *o.SkuId.Get()
}

// GetSkuIdOk returns a tuple with the SkuId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineUpdateRequest) GetSkuIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SkuId.Get(), o.SkuId.IsSet()
}

// HasSkuId returns a boolean if a field has been set.
func (o *ExpectedMachineUpdateRequest) HasSkuId() bool {
	if o != nil && o.SkuId.IsSet() {
		return true
	}

	return false
}

// SetSkuId gets a reference to the given NullableString and assigns it to the SkuId field.
func (o *ExpectedMachineUpdateRequest) SetSkuId(v string) {
	o.SkuId.Set(&v)
}

// SetSkuIdNil sets the value for SkuId to be an explicit nil
func (o *ExpectedMachineUpdateRequest) SetSkuIdNil() {
	o.SkuId.Set(nil)
}

// UnsetSkuId ensures that no value is present for SkuId, not even an explicit nil
func (o *ExpectedMachineUpdateRequest) UnsetSkuId() {
	o.SkuId.Unset()
}

// GetRackId returns the RackId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineUpdateRequest) GetRackId() string {
	if o == nil || IsNil(o.RackId.Get()) {
		var ret string
		return ret
	}
	return *o.RackId.Get()
}

// GetRackIdOk returns a tuple with the RackId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineUpdateRequest) GetRackIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RackId.Get(), o.RackId.IsSet()
}

// HasRackId returns a boolean if a field has been set.
func (o *ExpectedMachineUpdateRequest) HasRackId() bool {
	if o != nil && o.RackId.IsSet() {
		return true
	}

	return false
}

// SetRackId gets a reference to the given NullableString and assigns it to the RackId field.
func (o *ExpectedMachineUpdateRequest) SetRackId(v string) {
	o.RackId.Set(&v)
}

// SetRackIdNil sets the value for RackId to be an explicit nil
func (o *ExpectedMachineUpdateRequest) SetRackIdNil() {
	o.RackId.Set(nil)
}

// UnsetRackId ensures that no value is present for RackId, not even an explicit nil
func (o *ExpectedMachineUpdateRequest) UnsetRackId() {
	o.RackId.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineUpdateRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ExpectedMachineUpdateRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ExpectedMachineUpdateRequest) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *ExpectedMachineUpdateRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ExpectedMachineUpdateRequest) UnsetName() {
	o.Name.Unset()
}

// GetManufacturer returns the Manufacturer field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineUpdateRequest) GetManufacturer() string {
	if o == nil || IsNil(o.Manufacturer.Get()) {
		var ret string
		return ret
	}
	return *o.Manufacturer.Get()
}

// GetManufacturerOk returns a tuple with the Manufacturer field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineUpdateRequest) GetManufacturerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Manufacturer.Get(), o.Manufacturer.IsSet()
}

// HasManufacturer returns a boolean if a field has been set.
func (o *ExpectedMachineUpdateRequest) HasManufacturer() bool {
	if o != nil && o.Manufacturer.IsSet() {
		return true
	}

	return false
}

// SetManufacturer gets a reference to the given NullableString and assigns it to the Manufacturer field.
func (o *ExpectedMachineUpdateRequest) SetManufacturer(v string) {
	o.Manufacturer.Set(&v)
}

// SetManufacturerNil sets the value for Manufacturer to be an explicit nil
func (o *ExpectedMachineUpdateRequest) SetManufacturerNil() {
	o.Manufacturer.Set(nil)
}

// UnsetManufacturer ensures that no value is present for Manufacturer, not even an explicit nil
func (o *ExpectedMachineUpdateRequest) UnsetManufacturer() {
	o.Manufacturer.Unset()
}

// GetModel returns the Model field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineUpdateRequest) GetModel() string {
	if o == nil || IsNil(o.Model.Get()) {
		var ret string
		return ret
	}
	return *o.Model.Get()
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineUpdateRequest) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Model.Get(), o.Model.IsSet()
}

// HasModel returns a boolean if a field has been set.
func (o *ExpectedMachineUpdateRequest) HasModel() bool {
	if o != nil && o.Model.IsSet() {
		return true
	}

	return false
}

// SetModel gets a reference to the given NullableString and assigns it to the Model field.
func (o *ExpectedMachineUpdateRequest) SetModel(v string) {
	o.Model.Set(&v)
}

// SetModelNil sets the value for Model to be an explicit nil
func (o *ExpectedMachineUpdateRequest) SetModelNil() {
	o.Model.Set(nil)
}

// UnsetModel ensures that no value is present for Model, not even an explicit nil
func (o *ExpectedMachineUpdateRequest) UnsetModel() {
	o.Model.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineUpdateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineUpdateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ExpectedMachineUpdateRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ExpectedMachineUpdateRequest) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ExpectedMachineUpdateRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ExpectedMachineUpdateRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetFirmwareVersion returns the FirmwareVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineUpdateRequest) GetFirmwareVersion() string {
	if o == nil || IsNil(o.FirmwareVersion.Get()) {
		var ret string
		return ret
	}
	return *o.FirmwareVersion.Get()
}

// GetFirmwareVersionOk returns a tuple with the FirmwareVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineUpdateRequest) GetFirmwareVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FirmwareVersion.Get(), o.FirmwareVersion.IsSet()
}

// HasFirmwareVersion returns a boolean if a field has been set.
func (o *ExpectedMachineUpdateRequest) HasFirmwareVersion() bool {
	if o != nil && o.FirmwareVersion.IsSet() {
		return true
	}

	return false
}

// SetFirmwareVersion gets a reference to the given NullableString and assigns it to the FirmwareVersion field.
func (o *ExpectedMachineUpdateRequest) SetFirmwareVersion(v string) {
	o.FirmwareVersion.Set(&v)
}

// SetFirmwareVersionNil sets the value for FirmwareVersion to be an explicit nil
func (o *ExpectedMachineUpdateRequest) SetFirmwareVersionNil() {
	o.FirmwareVersion.Set(nil)
}

// UnsetFirmwareVersion ensures that no value is present for FirmwareVersion, not even an explicit nil
func (o *ExpectedMachineUpdateRequest) UnsetFirmwareVersion() {
	o.FirmwareVersion.Unset()
}

// GetSlotId returns the SlotId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineUpdateRequest) GetSlotId() int32 {
	if o == nil || IsNil(o.SlotId.Get()) {
		var ret int32
		return ret
	}
	return *o.SlotId.Get()
}

// GetSlotIdOk returns a tuple with the SlotId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineUpdateRequest) GetSlotIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SlotId.Get(), o.SlotId.IsSet()
}

// HasSlotId returns a boolean if a field has been set.
func (o *ExpectedMachineUpdateRequest) HasSlotId() bool {
	if o != nil && o.SlotId.IsSet() {
		return true
	}

	return false
}

// SetSlotId gets a reference to the given NullableInt32 and assigns it to the SlotId field.
func (o *ExpectedMachineUpdateRequest) SetSlotId(v int32) {
	o.SlotId.Set(&v)
}

// SetSlotIdNil sets the value for SlotId to be an explicit nil
func (o *ExpectedMachineUpdateRequest) SetSlotIdNil() {
	o.SlotId.Set(nil)
}

// UnsetSlotId ensures that no value is present for SlotId, not even an explicit nil
func (o *ExpectedMachineUpdateRequest) UnsetSlotId() {
	o.SlotId.Unset()
}

// GetTrayIdx returns the TrayIdx field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineUpdateRequest) GetTrayIdx() int32 {
	if o == nil || IsNil(o.TrayIdx.Get()) {
		var ret int32
		return ret
	}
	return *o.TrayIdx.Get()
}

// GetTrayIdxOk returns a tuple with the TrayIdx field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineUpdateRequest) GetTrayIdxOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TrayIdx.Get(), o.TrayIdx.IsSet()
}

// HasTrayIdx returns a boolean if a field has been set.
func (o *ExpectedMachineUpdateRequest) HasTrayIdx() bool {
	if o != nil && o.TrayIdx.IsSet() {
		return true
	}

	return false
}

// SetTrayIdx gets a reference to the given NullableInt32 and assigns it to the TrayIdx field.
func (o *ExpectedMachineUpdateRequest) SetTrayIdx(v int32) {
	o.TrayIdx.Set(&v)
}

// SetTrayIdxNil sets the value for TrayIdx to be an explicit nil
func (o *ExpectedMachineUpdateRequest) SetTrayIdxNil() {
	o.TrayIdx.Set(nil)
}

// UnsetTrayIdx ensures that no value is present for TrayIdx, not even an explicit nil
func (o *ExpectedMachineUpdateRequest) UnsetTrayIdx() {
	o.TrayIdx.Unset()
}

// GetHostId returns the HostId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineUpdateRequest) GetHostId() int32 {
	if o == nil || IsNil(o.HostId.Get()) {
		var ret int32
		return ret
	}
	return *o.HostId.Get()
}

// GetHostIdOk returns a tuple with the HostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineUpdateRequest) GetHostIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.HostId.Get(), o.HostId.IsSet()
}

// HasHostId returns a boolean if a field has been set.
func (o *ExpectedMachineUpdateRequest) HasHostId() bool {
	if o != nil && o.HostId.IsSet() {
		return true
	}

	return false
}

// SetHostId gets a reference to the given NullableInt32 and assigns it to the HostId field.
func (o *ExpectedMachineUpdateRequest) SetHostId(v int32) {
	o.HostId.Set(&v)
}

// SetHostIdNil sets the value for HostId to be an explicit nil
func (o *ExpectedMachineUpdateRequest) SetHostIdNil() {
	o.HostId.Set(nil)
}

// UnsetHostId ensures that no value is present for HostId, not even an explicit nil
func (o *ExpectedMachineUpdateRequest) UnsetHostId() {
	o.HostId.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ExpectedMachineUpdateRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedMachineUpdateRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ExpectedMachineUpdateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ExpectedMachineUpdateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o ExpectedMachineUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedMachineUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if o.BmcMacAddress.IsSet() {
		toSerialize["bmcMacAddress"] = o.BmcMacAddress.Get()
	}
	if o.BmcUsername.IsSet() {
		toSerialize["bmcUsername"] = o.BmcUsername.Get()
	}
	if o.BmcPassword.IsSet() {
		toSerialize["bmcPassword"] = o.BmcPassword.Get()
	}
	if o.ChassisSerialNumber.IsSet() {
		toSerialize["chassisSerialNumber"] = o.ChassisSerialNumber.Get()
	}
	if o.FallbackDPUSerialNumbers != nil {
		toSerialize["fallbackDPUSerialNumbers"] = o.FallbackDPUSerialNumbers
	}
	if o.SkuId.IsSet() {
		toSerialize["skuId"] = o.SkuId.Get()
	}
	if o.RackId.IsSet() {
		toSerialize["rackId"] = o.RackId.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Manufacturer.IsSet() {
		toSerialize["manufacturer"] = o.Manufacturer.Get()
	}
	if o.Model.IsSet() {
		toSerialize["model"] = o.Model.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.FirmwareVersion.IsSet() {
		toSerialize["firmwareVersion"] = o.FirmwareVersion.Get()
	}
	if o.SlotId.IsSet() {
		toSerialize["slotId"] = o.SlotId.Get()
	}
	if o.TrayIdx.IsSet() {
		toSerialize["trayIdx"] = o.TrayIdx.Get()
	}
	if o.HostId.IsSet() {
		toSerialize["hostId"] = o.HostId.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

type NullableExpectedMachineUpdateRequest struct {
	value *ExpectedMachineUpdateRequest
	isSet bool
}

func (v NullableExpectedMachineUpdateRequest) Get() *ExpectedMachineUpdateRequest {
	return v.value
}

func (v *NullableExpectedMachineUpdateRequest) Set(val *ExpectedMachineUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedMachineUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedMachineUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedMachineUpdateRequest(val *ExpectedMachineUpdateRequest) *NullableExpectedMachineUpdateRequest {
	return &NullableExpectedMachineUpdateRequest{value: val, isSet: true}
}

func (v NullableExpectedMachineUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedMachineUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
