/*
NVIDIA Bare Metal Manager REST API

NVIDIA Bare Metal Manager REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Bare Metal Manager datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the SiteMachineStatsByHealth type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteMachineStatsByHealth{}

// SiteMachineStatsByHealth Machine stats for a Site by health
type SiteMachineStatsByHealth struct {
	Healthy *int32 `json:"healthy,omitempty"`
	Unhealthy *int32 `json:"unhealthy,omitempty"`
}

// NewSiteMachineStatsByHealth instantiates a new SiteMachineStatsByHealth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteMachineStatsByHealth() *SiteMachineStatsByHealth {
	this := SiteMachineStatsByHealth{}
	return &this
}

// NewSiteMachineStatsByHealthWithDefaults instantiates a new SiteMachineStatsByHealth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteMachineStatsByHealthWithDefaults() *SiteMachineStatsByHealth {
	this := SiteMachineStatsByHealth{}
	return &this
}

// GetHealthy returns the Healthy field value if set, zero value otherwise.
func (o *SiteMachineStatsByHealth) GetHealthy() int32 {
	if o == nil || IsNil(o.Healthy) {
		var ret int32
		return ret
	}
	return *o.Healthy
}

// GetHealthyOk returns a tuple with the Healthy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStatsByHealth) GetHealthyOk() (*int32, bool) {
	if o == nil || IsNil(o.Healthy) {
		return nil, false
	}
	return o.Healthy, true
}

// HasHealthy returns a boolean if a field has been set.
func (o *SiteMachineStatsByHealth) HasHealthy() bool {
	if o != nil && !IsNil(o.Healthy) {
		return true
	}

	return false
}

// SetHealthy gets a reference to the given int32 and assigns it to the Healthy field.
func (o *SiteMachineStatsByHealth) SetHealthy(v int32) {
	o.Healthy = &v
}

// GetUnhealthy returns the Unhealthy field value if set, zero value otherwise.
func (o *SiteMachineStatsByHealth) GetUnhealthy() int32 {
	if o == nil || IsNil(o.Unhealthy) {
		var ret int32
		return ret
	}
	return *o.Unhealthy
}

// GetUnhealthyOk returns a tuple with the Unhealthy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStatsByHealth) GetUnhealthyOk() (*int32, bool) {
	if o == nil || IsNil(o.Unhealthy) {
		return nil, false
	}
	return o.Unhealthy, true
}

// HasUnhealthy returns a boolean if a field has been set.
func (o *SiteMachineStatsByHealth) HasUnhealthy() bool {
	if o != nil && !IsNil(o.Unhealthy) {
		return true
	}

	return false
}

// SetUnhealthy gets a reference to the given int32 and assigns it to the Unhealthy field.
func (o *SiteMachineStatsByHealth) SetUnhealthy(v int32) {
	o.Unhealthy = &v
}

func (o SiteMachineStatsByHealth) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteMachineStatsByHealth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Healthy) {
		toSerialize["healthy"] = o.Healthy
	}
	if !IsNil(o.Unhealthy) {
		toSerialize["unhealthy"] = o.Unhealthy
	}
	return toSerialize, nil
}

type NullableSiteMachineStatsByHealth struct {
	value *SiteMachineStatsByHealth
	isSet bool
}

func (v NullableSiteMachineStatsByHealth) Get() *SiteMachineStatsByHealth {
	return v.value
}

func (v *NullableSiteMachineStatsByHealth) Set(val *SiteMachineStatsByHealth) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteMachineStatsByHealth) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteMachineStatsByHealth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteMachineStatsByHealth(val *SiteMachineStatsByHealth) *NullableSiteMachineStatsByHealth {
	return &NullableSiteMachineStatsByHealth{value: val, isSet: true}
}

func (v NullableSiteMachineStatsByHealth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteMachineStatsByHealth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


