/*
NVIDIA Bare Metal Manager REST API

NVIDIA Bare Metal Manager REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Bare Metal Manager datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the SiteMachineStatsByAllocation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteMachineStatsByAllocation{}

// SiteMachineStatsByAllocation Machine stats for a Site by allocation
type SiteMachineStatsByAllocation struct {
	AllocatedInUse *int32 `json:"allocatedInUse,omitempty"`
	AllocatedNotInUse *int32 `json:"allocatedNotInUse,omitempty"`
	Unallocated *int32 `json:"unallocated,omitempty"`
}

// NewSiteMachineStatsByAllocation instantiates a new SiteMachineStatsByAllocation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteMachineStatsByAllocation() *SiteMachineStatsByAllocation {
	this := SiteMachineStatsByAllocation{}
	return &this
}

// NewSiteMachineStatsByAllocationWithDefaults instantiates a new SiteMachineStatsByAllocation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteMachineStatsByAllocationWithDefaults() *SiteMachineStatsByAllocation {
	this := SiteMachineStatsByAllocation{}
	return &this
}

// GetAllocatedInUse returns the AllocatedInUse field value if set, zero value otherwise.
func (o *SiteMachineStatsByAllocation) GetAllocatedInUse() int32 {
	if o == nil || IsNil(o.AllocatedInUse) {
		var ret int32
		return ret
	}
	return *o.AllocatedInUse
}

// GetAllocatedInUseOk returns a tuple with the AllocatedInUse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStatsByAllocation) GetAllocatedInUseOk() (*int32, bool) {
	if o == nil || IsNil(o.AllocatedInUse) {
		return nil, false
	}
	return o.AllocatedInUse, true
}

// HasAllocatedInUse returns a boolean if a field has been set.
func (o *SiteMachineStatsByAllocation) HasAllocatedInUse() bool {
	if o != nil && !IsNil(o.AllocatedInUse) {
		return true
	}

	return false
}

// SetAllocatedInUse gets a reference to the given int32 and assigns it to the AllocatedInUse field.
func (o *SiteMachineStatsByAllocation) SetAllocatedInUse(v int32) {
	o.AllocatedInUse = &v
}

// GetAllocatedNotInUse returns the AllocatedNotInUse field value if set, zero value otherwise.
func (o *SiteMachineStatsByAllocation) GetAllocatedNotInUse() int32 {
	if o == nil || IsNil(o.AllocatedNotInUse) {
		var ret int32
		return ret
	}
	return *o.AllocatedNotInUse
}

// GetAllocatedNotInUseOk returns a tuple with the AllocatedNotInUse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStatsByAllocation) GetAllocatedNotInUseOk() (*int32, bool) {
	if o == nil || IsNil(o.AllocatedNotInUse) {
		return nil, false
	}
	return o.AllocatedNotInUse, true
}

// HasAllocatedNotInUse returns a boolean if a field has been set.
func (o *SiteMachineStatsByAllocation) HasAllocatedNotInUse() bool {
	if o != nil && !IsNil(o.AllocatedNotInUse) {
		return true
	}

	return false
}

// SetAllocatedNotInUse gets a reference to the given int32 and assigns it to the AllocatedNotInUse field.
func (o *SiteMachineStatsByAllocation) SetAllocatedNotInUse(v int32) {
	o.AllocatedNotInUse = &v
}

// GetUnallocated returns the Unallocated field value if set, zero value otherwise.
func (o *SiteMachineStatsByAllocation) GetUnallocated() int32 {
	if o == nil || IsNil(o.Unallocated) {
		var ret int32
		return ret
	}
	return *o.Unallocated
}

// GetUnallocatedOk returns a tuple with the Unallocated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStatsByAllocation) GetUnallocatedOk() (*int32, bool) {
	if o == nil || IsNil(o.Unallocated) {
		return nil, false
	}
	return o.Unallocated, true
}

// HasUnallocated returns a boolean if a field has been set.
func (o *SiteMachineStatsByAllocation) HasUnallocated() bool {
	if o != nil && !IsNil(o.Unallocated) {
		return true
	}

	return false
}

// SetUnallocated gets a reference to the given int32 and assigns it to the Unallocated field.
func (o *SiteMachineStatsByAllocation) SetUnallocated(v int32) {
	o.Unallocated = &v
}

func (o SiteMachineStatsByAllocation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteMachineStatsByAllocation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AllocatedInUse) {
		toSerialize["allocatedInUse"] = o.AllocatedInUse
	}
	if !IsNil(o.AllocatedNotInUse) {
		toSerialize["allocatedNotInUse"] = o.AllocatedNotInUse
	}
	if !IsNil(o.Unallocated) {
		toSerialize["unallocated"] = o.Unallocated
	}
	return toSerialize, nil
}

type NullableSiteMachineStatsByAllocation struct {
	value *SiteMachineStatsByAllocation
	isSet bool
}

func (v NullableSiteMachineStatsByAllocation) Get() *SiteMachineStatsByAllocation {
	return v.value
}

func (v *NullableSiteMachineStatsByAllocation) Set(val *SiteMachineStatsByAllocation) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteMachineStatsByAllocation) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteMachineStatsByAllocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteMachineStatsByAllocation(val *SiteMachineStatsByAllocation) *NullableSiteMachineStatsByAllocation {
	return &NullableSiteMachineStatsByAllocation{value: val, isSet: true}
}

func (v NullableSiteMachineStatsByAllocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteMachineStatsByAllocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


