/*
NVIDIA Bare Metal Manager REST API

NVIDIA Bare Metal Manager REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Bare Metal Manager datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the SiteMachineStatsByStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteMachineStatsByStatus{}

// SiteMachineStatsByStatus Machine stats for a Site by status
type SiteMachineStatsByStatus struct {
	Decommissioned *int32 `json:"Decommissioned,omitempty"`
	Error *int32 `json:"Error,omitempty"`
	Initializing *int32 `json:"Initializing,omitempty"`
	InUse *int32 `json:"InUse,omitempty"`
	Maintenance *int32 `json:"Maintenance,omitempty"`
	Ready *int32 `json:"Ready,omitempty"`
	Reset *int32 `json:"Reset,omitempty"`
	Unknown *int32 `json:"Unknown,omitempty"`
}

// NewSiteMachineStatsByStatus instantiates a new SiteMachineStatsByStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteMachineStatsByStatus() *SiteMachineStatsByStatus {
	this := SiteMachineStatsByStatus{}
	return &this
}

// NewSiteMachineStatsByStatusWithDefaults instantiates a new SiteMachineStatsByStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteMachineStatsByStatusWithDefaults() *SiteMachineStatsByStatus {
	this := SiteMachineStatsByStatus{}
	return &this
}

// GetDecommissioned returns the Decommissioned field value if set, zero value otherwise.
func (o *SiteMachineStatsByStatus) GetDecommissioned() int32 {
	if o == nil || IsNil(o.Decommissioned) {
		var ret int32
		return ret
	}
	return *o.Decommissioned
}

// GetDecommissionedOk returns a tuple with the Decommissioned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStatsByStatus) GetDecommissionedOk() (*int32, bool) {
	if o == nil || IsNil(o.Decommissioned) {
		return nil, false
	}
	return o.Decommissioned, true
}

// HasDecommissioned returns a boolean if a field has been set.
func (o *SiteMachineStatsByStatus) HasDecommissioned() bool {
	if o != nil && !IsNil(o.Decommissioned) {
		return true
	}

	return false
}

// SetDecommissioned gets a reference to the given int32 and assigns it to the Decommissioned field.
func (o *SiteMachineStatsByStatus) SetDecommissioned(v int32) {
	o.Decommissioned = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *SiteMachineStatsByStatus) GetError() int32 {
	if o == nil || IsNil(o.Error) {
		var ret int32
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStatsByStatus) GetErrorOk() (*int32, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *SiteMachineStatsByStatus) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given int32 and assigns it to the Error field.
func (o *SiteMachineStatsByStatus) SetError(v int32) {
	o.Error = &v
}

// GetInitializing returns the Initializing field value if set, zero value otherwise.
func (o *SiteMachineStatsByStatus) GetInitializing() int32 {
	if o == nil || IsNil(o.Initializing) {
		var ret int32
		return ret
	}
	return *o.Initializing
}

// GetInitializingOk returns a tuple with the Initializing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStatsByStatus) GetInitializingOk() (*int32, bool) {
	if o == nil || IsNil(o.Initializing) {
		return nil, false
	}
	return o.Initializing, true
}

// HasInitializing returns a boolean if a field has been set.
func (o *SiteMachineStatsByStatus) HasInitializing() bool {
	if o != nil && !IsNil(o.Initializing) {
		return true
	}

	return false
}

// SetInitializing gets a reference to the given int32 and assigns it to the Initializing field.
func (o *SiteMachineStatsByStatus) SetInitializing(v int32) {
	o.Initializing = &v
}

// GetInUse returns the InUse field value if set, zero value otherwise.
func (o *SiteMachineStatsByStatus) GetInUse() int32 {
	if o == nil || IsNil(o.InUse) {
		var ret int32
		return ret
	}
	return *o.InUse
}

// GetInUseOk returns a tuple with the InUse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStatsByStatus) GetInUseOk() (*int32, bool) {
	if o == nil || IsNil(o.InUse) {
		return nil, false
	}
	return o.InUse, true
}

// HasInUse returns a boolean if a field has been set.
func (o *SiteMachineStatsByStatus) HasInUse() bool {
	if o != nil && !IsNil(o.InUse) {
		return true
	}

	return false
}

// SetInUse gets a reference to the given int32 and assigns it to the InUse field.
func (o *SiteMachineStatsByStatus) SetInUse(v int32) {
	o.InUse = &v
}

// GetMaintenance returns the Maintenance field value if set, zero value otherwise.
func (o *SiteMachineStatsByStatus) GetMaintenance() int32 {
	if o == nil || IsNil(o.Maintenance) {
		var ret int32
		return ret
	}
	return *o.Maintenance
}

// GetMaintenanceOk returns a tuple with the Maintenance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStatsByStatus) GetMaintenanceOk() (*int32, bool) {
	if o == nil || IsNil(o.Maintenance) {
		return nil, false
	}
	return o.Maintenance, true
}

// HasMaintenance returns a boolean if a field has been set.
func (o *SiteMachineStatsByStatus) HasMaintenance() bool {
	if o != nil && !IsNil(o.Maintenance) {
		return true
	}

	return false
}

// SetMaintenance gets a reference to the given int32 and assigns it to the Maintenance field.
func (o *SiteMachineStatsByStatus) SetMaintenance(v int32) {
	o.Maintenance = &v
}

// GetReady returns the Ready field value if set, zero value otherwise.
func (o *SiteMachineStatsByStatus) GetReady() int32 {
	if o == nil || IsNil(o.Ready) {
		var ret int32
		return ret
	}
	return *o.Ready
}

// GetReadyOk returns a tuple with the Ready field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStatsByStatus) GetReadyOk() (*int32, bool) {
	if o == nil || IsNil(o.Ready) {
		return nil, false
	}
	return o.Ready, true
}

// HasReady returns a boolean if a field has been set.
func (o *SiteMachineStatsByStatus) HasReady() bool {
	if o != nil && !IsNil(o.Ready) {
		return true
	}

	return false
}

// SetReady gets a reference to the given int32 and assigns it to the Ready field.
func (o *SiteMachineStatsByStatus) SetReady(v int32) {
	o.Ready = &v
}

// GetReset returns the Reset field value if set, zero value otherwise.
func (o *SiteMachineStatsByStatus) GetReset() int32 {
	if o == nil || IsNil(o.Reset) {
		var ret int32
		return ret
	}
	return *o.Reset
}

// GetResetOk returns a tuple with the Reset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStatsByStatus) GetResetOk() (*int32, bool) {
	if o == nil || IsNil(o.Reset) {
		return nil, false
	}
	return o.Reset, true
}

// HasReset returns a boolean if a field has been set.
func (o *SiteMachineStatsByStatus) HasReset() bool {
	if o != nil && !IsNil(o.Reset) {
		return true
	}

	return false
}

// SetReset gets a reference to the given int32 and assigns it to the Reset field.
func (o *SiteMachineStatsByStatus) SetReset(v int32) {
	o.Reset = &v
}

// GetUnknown returns the Unknown field value if set, zero value otherwise.
func (o *SiteMachineStatsByStatus) GetUnknown() int32 {
	if o == nil || IsNil(o.Unknown) {
		var ret int32
		return ret
	}
	return *o.Unknown
}

// GetUnknownOk returns a tuple with the Unknown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStatsByStatus) GetUnknownOk() (*int32, bool) {
	if o == nil || IsNil(o.Unknown) {
		return nil, false
	}
	return o.Unknown, true
}

// HasUnknown returns a boolean if a field has been set.
func (o *SiteMachineStatsByStatus) HasUnknown() bool {
	if o != nil && !IsNil(o.Unknown) {
		return true
	}

	return false
}

// SetUnknown gets a reference to the given int32 and assigns it to the Unknown field.
func (o *SiteMachineStatsByStatus) SetUnknown(v int32) {
	o.Unknown = &v
}

func (o SiteMachineStatsByStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteMachineStatsByStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Decommissioned) {
		toSerialize["Decommissioned"] = o.Decommissioned
	}
	if !IsNil(o.Error) {
		toSerialize["Error"] = o.Error
	}
	if !IsNil(o.Initializing) {
		toSerialize["Initializing"] = o.Initializing
	}
	if !IsNil(o.InUse) {
		toSerialize["InUse"] = o.InUse
	}
	if !IsNil(o.Maintenance) {
		toSerialize["Maintenance"] = o.Maintenance
	}
	if !IsNil(o.Ready) {
		toSerialize["Ready"] = o.Ready
	}
	if !IsNil(o.Reset) {
		toSerialize["Reset"] = o.Reset
	}
	if !IsNil(o.Unknown) {
		toSerialize["Unknown"] = o.Unknown
	}
	return toSerialize, nil
}

type NullableSiteMachineStatsByStatus struct {
	value *SiteMachineStatsByStatus
	isSet bool
}

func (v NullableSiteMachineStatsByStatus) Get() *SiteMachineStatsByStatus {
	return v.value
}

func (v *NullableSiteMachineStatsByStatus) Set(val *SiteMachineStatsByStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteMachineStatsByStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteMachineStatsByStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteMachineStatsByStatus(val *SiteMachineStatsByStatus) *NullableSiteMachineStatsByStatus {
	return &NullableSiteMachineStatsByStatus{value: val, isSet: true}
}

func (v NullableSiteMachineStatsByStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteMachineStatsByStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


